In [12]:
#Bootsrtap cross Validation

In [13]:
from sklearn.utils import resample

data = [1, 2, 3, 4, 5, 6]

outputBoot_resample = resample(data, replace=True, n_samples=4, random_state=1)

print('Bootstrap Sample: %s' % outputBoot_resample)

result = [x for x in data if x not in outputBoot_resample]

print('OOB Sample: %s' % result)

Bootstrap Sample: [6, 4, 5, 1]
OOB Sample: [2, 3]


In [14]:
#HoldOut Cross validation

In [15]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm

iris = datasets.load_iris()
iris.data.shape, iris.target.shape


X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.4, random_state=0)

X_train.shape, y_train.shape

X_test.shape, y_test.shape


clf = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)
clf.score(X_test, y_test)  #

0.9666666666666667

In [16]:
#Leave one Out Cross validation

In [17]:
import numpy as np
from sklearn.model_selection import LeaveOneOut

X = np.array([[0, 0], [1, 1], [2, 2], [3, 3]])
Y = [0, 1, 0, 1]


loo = LeaveOneOut()
loo.get_n_splits(X)
print(loo.get_n_splits(X))
for train, test in loo.split(X):
    print(train, test)
    

4
[1 2 3] [0]
[0 2 3] [1]
[0 1 3] [2]
[0 1 2] [3]


In [10]:
#Leave P out cross validation

In [11]:
from sklearn.model_selection import LeavePOut
X = [[0, 0], [1, 1], [2, 2], [3, 3]]

Y = [0, 1, 0, 1]
lpo = LeavePOut(2)

print(lpo.get_n_splits(X))
print(lpo)

for train, test in lpo.split(X):
    print(train, test)

6
LeavePOut(p=2)
[2 3] [0 1]
[1 3] [0 2]
[1 2] [0 3]
[0 3] [1 2]
[0 2] [1 3]
[0 1] [2 3]


In [18]:
#KFOLD

In [25]:
import numpy as np
from sklearn.model_selection import KFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([1, 2, 3, 4])
kf = KFold(n_splits=2)
kf.get_n_splits(X)

print(kf)  

for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

KFold(n_splits=2, random_state=None, shuffle=False)
TRAIN: [2 3] TEST: [0 1]
TRAIN: [0 1] TEST: [2 3]


In [20]:
#Startified KFOLD

In [22]:
import numpy as np
from sklearn.model_selection import StratifiedKFold
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([0, 0, 1, 1])
skf = StratifiedKFold(n_splits=2)
skf.get_n_splits(X, y)

print(skf)  

for train_index, test_index in skf.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
   

StratifiedKFold(n_splits=2, random_state=None, shuffle=False)
TRAIN: [1 3] TEST: [0 2]
TRAIN: [0 2] TEST: [1 3]


In [23]:
#TimeSeriesSplit

In [24]:

   

from sklearn.model_selection import TimeSeriesSplit

X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([1, 2, 3, 4, 5, 6])

tscv = TimeSeriesSplit(n_splits=3,max_train_size= None)
print(tscv)  

for train, test in tscv.split(X):
    print("%s %s" % (train, test)) 

TimeSeriesSplit(max_train_size=None, n_splits=3)
[0 1 2] [3]
[0 1 2 3] [4]
[0 1 2 3 4] [5]
